[tool.poetry]
name = "cv-analyzer"
version = "0.1.0"
description = ""
authors = ["Carlos"]
readme = "README.md"

[tool.poetry.dependencies]
python = "Ë†3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
